-- to remove?
-- Packer
--local use = require('packer').use
--require('packer').startup(function()
--  use 'neovim/nvim-lspconfig' -- Collection of configurations for built-in LSP client
--  use 'hrsh7th/nvim-cmp' -- Autocompletion plugin
--  use 'hrsh7th/cmp-nvim-lsp' -- LSP source for nvim-cmp
--  use 'saadparwaiz1/cmp_luasnip' -- Snippets source for nvim-cmp
--  use 'L3MON4D3/LuaSnip' -- Snippets plugin
--
--  -- Telescope (file browsing and fuzzy search)
--  use 'nvim-lua/plenary.nvim'
--  use {
--    'nvim-telescope/telescope.nvim',
--    requires = { {'nvim-lua/plenary.nvim'} }
--  }
--  use {
--    'nvim-telescope/telescope-fzf-native.nvim',
--    run = 'cmake -S. -Bbuild -DCMAKE_BUILD_TYPE=Release && cmake --build build --config Release && cmake --install build --prefix build'
--  }
--
--  -- Markdown previewer
--  use {
--    'iamcco/markdown-preview.nvim',
--    run = function() vim.fn["mkdp#util#install"]() end,
--  }
--end)
--
